---
- name: install core packages
  hosts: "{{ my_hosts | d([]) }}"
  become: true

  tasks:
    - name: install core packages
      ansible.builtin.apt:
        name:
          - prometheus-node-exporter
          - nfs-common
        update_cache: true
