---
- name: Install microk8s
  hosts: "{{ my_hosts | d([]) }}"
  become: true

  tasks:
    - name: Install microk8s
      community.general.snap:
        classic: true
        name: microk8s

    - name: Add user permissions
      ansible.builtin.shell: "usermod -aG microk8s {{ lookup('env', 'USER') }}"
